wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.8
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
dataset:
  desc: null
  value: Dataset
dataset_args:
  desc: null
  value:
    batch_size: 512
    test_fraction: 0.3
model:
  desc: null
  value: RetrievalModel
network:
  desc: null
  value: retrieval_basic_factorization
network_args:
  desc: null
  value:
    embedding_dimension: 32
train_args:
  desc: null
  value:
    epochs: 1
    learning_rate: 0.01
    optimizer: SGD
